# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [4]:
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [5]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [14]:
array = np.arange(9)
mat = array.reshape(3,3)
mat[np.eye(3, dtype=bool)] = 0

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [17]:
mat1 = np.ones((5,5))
mat_with_border = np.pad(mat1, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [42]:
M = np.random.random((5,5))
print(M)
M_n = (M - np.mean(M)) / np.std(M)
print(M_n)
print()
print(f"{np.mean(M_n):.2f}")
print()
print(f"{np.std(M_n):.1f}")

[[0.70496776 0.28373027 0.08290279 0.51141337 0.18608046]
 [0.8887     0.86922873 0.27654824 0.51931246 0.71968525]
 [0.07134916 0.81415346 0.92831846 0.65372665 0.75375773]
 [0.19871397 0.13573744 0.9576319  0.5059908  0.51006409]
 [0.13497273 0.87125722 0.27837535 0.24329728 0.0175387 ]]
[[ 0.71884422 -0.65585364 -1.31124904  0.08718438 -0.97453135]
 [ 1.31844972  1.25490574 -0.67929202  0.11296285  0.76687438]
 [-1.34895402  1.07516898  1.44774358  0.55162017  0.87806905]
 [-0.9333022  -1.1388245   1.54340726  0.06948796  0.08278104]
 [-1.14132012  1.26152568 -0.67332929 -0.78780571 -1.52456311]]

-0.00

1.0


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [49]:
M1 = np.ones((5,3))
M2 = np.ones((3,2))
M = np.dot(M1, M2)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [62]:
x = np.linspace(0, 1, 12)
print(x)
x_10 = x[1:-1]
print(x_10)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [67]:
array = np.random.uniform(-3, 12, 10)
array_s = np.sort(array)
array_s

array([-2.74703022, -2.32080159, -1.31668984,  4.21525477,  4.46833271,
        4.69431422,  8.13849873,  8.81211468, 10.34251384, 10.83617382])

#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [73]:
array = np.random.randint(0, 100, 10)
print(array)
array[[np.argmax(array),np.argmin(array)]] = [np.negative(array[np.argmax(array)]), np.median(array)]
print(array)

[15 85  3 70 15 66 72 79 96 92]
[ 15  85  71  70  15  66  72  79 -96  92]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [84]:
n = 5
p = 8
M = np.zeros((n,n))
elements = np.random.choice(n*n, p, replace=False)
print(elements)
np.put(M, elements, 1)
print(M)

[11 24  7 21  8 23 16 10]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1.]]


#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [90]:
M = np.random.random((5,10))
media_righe = M.mean(axis=1, keepdims=True)
M_new = M - media_righe

array([[ 0.26493253,  0.15123147,  0.24014495, -0.41441394, -0.07585516,
         0.14666952, -0.38645233,  0.27500207, -0.47179704,  0.27053794],
       [-0.53749214, -0.15404366,  0.08631968, -0.02786233, -0.50840393,
         0.34193286,  0.0372262 ,  0.30924055,  0.35644919,  0.09663357],
       [-0.35936324,  0.53520059,  0.17716256, -0.17516125, -0.29868355,
         0.32313936,  0.15957012, -0.40023829, -0.07248246,  0.11085616],
       [-0.39057367,  0.24157331, -0.21662171, -0.27334963,  0.54989121,
        -0.20942051,  0.45461174, -0.1819509 ,  0.34598746, -0.32014729],
       [-0.11326861, -0.18578423,  0.44239893,  0.20947153, -0.2063117 ,
        -0.03791921,  0.27904169,  0.255885  , -0.37120813, -0.27230527]])